name: Update Project Board on Release

on:
  release:
    types: [published]  # Trigger workflow on published releases

jobs:
  update-board:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Get Latest Release
        id: get_latest_release
        run: |
          RELEASE_ID=$(curl -s -H "Authorization: token ${{ secrets.LCFRAPI_GITHUB_TOKEN }}" "https://api.github.com/repos/${{ github.repository }}/releases/latest" | jq -r '.id')
          echo "::set-output name=release_id::$RELEASE_ID"

      - name: Push Release to Project Board
        run: |
          RELEASE_ID=${{ steps.get_latest_release.outputs.release_id }}
          curl -X POST -H "Authorization: token ${{ secrets.LCFRAPI_GITHUB_TOKEN }}" -H "Accept: application/vnd.github.inertia-preview+json" https://api.github.com/projects/columns/2/cards -d "{\"content_id\": \"$RELEASE_ID\", \"content_type\": \"Release\"}"
